import type { ArticleItem } from '../types';

// This file is auto-generated by scripts/build-posts.mjs
export const posts: ArticleItem[] = [
  {
    "id": "reading-across-two-information-worlds-en",
    "title": "Reading Across Two Information Worlds",
    "slug": "reading-across-two-information-worlds",
    "locale": "en",
    "translationKey": "reading-across-two-information-worlds",
    "status": "published",
    "publishedAt": "2026-04-16",
    "summary": "A short note on why East Meridian treats English and Chinese information streams as complementary, not interchangeable.",
    "tags": [
      "information",
      "process",
      "china"
    ],
    "featured": true,
    "filePath": "content/posts/2026-04-16-reading-across-two-information-worlds.en.md",
    "markdown": "The most useful macro work often begins before a forecast. It begins with deciding which information world is allowed to shape the question.\n\nEnglish-language market writing is usually strong on global framing: rates, liquidity, balance-sheet plumbing, positioning, and the language of international capital. Chinese-language material is often closer to the local texture: policy wording, industrial mood, credit stress, property sentiment, and the words people use before they become translated categories.\n\nNeither side is complete. Each one has blind spots that feel obvious only after you spend time in the other.\n\nFor me, the point is not to average the two. The point is to compare them. When the same development appears in both worlds with different emphasis, that difference is often the signal. Sometimes the English-language world sees a global asset-pricing problem while the Chinese-language world sees a domestic policy tradeoff. Sometimes the Chinese-language world captures a change in tone before it is visible in global commentary.\n\nEast Meridian exists partly to make this input structure visible. It is a place to track what I read, listen to, and revisit, but also a reminder that information edge often comes from translation gaps rather than faster headlines.",
    "excerpt": "A short note on why East Meridian treats English and Chinese information streams as complementary, not interchangeable.",
    "readingTimeMinutes": 1,
    "wordCount": 1278,
    "path": "/writing/reading-across-two-information-worlds",
    "html": "<p>The most useful macro work often begins before a forecast. It begins with deciding which information world is allowed to shape the question.</p>\n<p>English-language market writing is usually strong on global framing: rates, liquidity, balance-sheet plumbing, positioning, and the language of international capital. Chinese-language material is often closer to the local texture: policy wording, industrial mood, credit stress, property sentiment, and the words people use before they become translated categories.</p>\n<p>Neither side is complete. Each one has blind spots that feel obvious only after you spend time in the other.</p>\n<p>For me, the point is not to average the two. The point is to compare them. When the same development appears in both worlds with different emphasis, that difference is often the signal. Sometimes the English-language world sees a global asset-pricing problem while the Chinese-language world sees a domestic policy tradeoff. Sometimes the Chinese-language world captures a change in tone before it is visible in global commentary.</p>\n<p>East Meridian exists partly to make this input structure visible. It is a place to track what I read, listen to, and revisit, but also a reminder that information edge often comes from translation gaps rather than faster headlines.</p>\n"
  },
  {
    "id": "reading-across-two-information-worlds-zh",
    "title": "在两个信息世界之间阅读",
    "slug": "reading-across-two-information-worlds",
    "locale": "zh",
    "translationKey": "reading-across-two-information-worlds",
    "status": "published",
    "publishedAt": "2026-04-16",
    "summary": "一篇短笔记，解释为什么东望子午会把中文和英文信息流视为互补关系，而不是彼此替代。",
    "tags": [
      "信息",
      "方法",
      "中国"
    ],
    "featured": true,
    "filePath": "content/posts/2026-04-16-reading-across-two-information-worlds.zh.md",
    "markdown": "真正有用的宏观工作，很多时候不是从预测开始，而是从决定由哪个信息世界来塑造问题开始。\n\n英文市场写作通常更擅长全球框架: 利率、流动性、资产负债表管道、仓位，以及国际资本熟悉的表达方式。中文材料则往往更接近本土肌理: 政策措辞、产业情绪、信用压力、地产体感，以及许多概念在被翻译成全球语言之前的原始说法。\n\n两边都不完整。每一个信息世界都有自己的盲点，而这些盲点往往只有在另一个信息世界里待久了之后才会变得明显。\n\n对我来说，重点不是把两边简单平均，而是比较它们。当同一件事在两个语境里被赋予不同权重时，这种差异本身经常就是信号。有时候，英文世界看到的是一个全球资产定价问题，而中文世界看到的是一个本土政策取舍。有时候，中文语境会先捕捉到语气变化，而全球评论还没有来得及吸收它。\n\n东望子午存在的一个原因，就是把这种输入结构变得可见。它既是我记录阅读、收听和反复回看的地方，也提醒我: 信息优势很多时候不是来自更快的标题，而是来自翻译缝隙。",
    "excerpt": "一篇短笔记，解释为什么东望子午会把中文和英文信息流视为互补关系，而不是彼此替代。",
    "readingTimeMinutes": 1,
    "wordCount": 416,
    "path": "/zh/writing/reading-across-two-information-worlds",
    "html": "<p>真正有用的宏观工作，很多时候不是从预测开始，而是从决定由哪个信息世界来塑造问题开始。</p>\n<p>英文市场写作通常更擅长全球框架: 利率、流动性、资产负债表管道、仓位，以及国际资本熟悉的表达方式。中文材料则往往更接近本土肌理: 政策措辞、产业情绪、信用压力、地产体感，以及许多概念在被翻译成全球语言之前的原始说法。</p>\n<p>两边都不完整。每一个信息世界都有自己的盲点，而这些盲点往往只有在另一个信息世界里待久了之后才会变得明显。</p>\n<p>对我来说，重点不是把两边简单平均，而是比较它们。当同一件事在两个语境里被赋予不同权重时，这种差异本身经常就是信号。有时候，英文世界看到的是一个全球资产定价问题，而中文世界看到的是一个本土政策取舍。有时候，中文语境会先捕捉到语气变化，而全球评论还没有来得及吸收它。</p>\n<p>东望子午存在的一个原因，就是把这种输入结构变得可见。它既是我记录阅读、收听和反复回看的地方，也提醒我: 信息优势很多时候不是来自更快的标题，而是来自翻译缝隙。</p>\n"
  },
  {
    "id": "why-market-notebooks-need-history-en",
    "title": "Why Market Notebooks Need History",
    "slug": "why-market-notebooks-need-history",
    "locale": "en",
    "translationKey": "why-market-notebooks-need-history",
    "status": "published",
    "publishedAt": "2026-04-10",
    "summary": "Markets price the present, but history helps define which futures are imaginable.",
    "tags": [
      "history",
      "method",
      "macro"
    ],
    "featured": false,
    "filePath": "content/posts/2026-04-10-why-market-notebooks-need-history.en.md",
    "markdown": "Markets are forward-looking, but investors are not free from the past. Institutions, political memories, industrial structures, and social expectations all limit what a market can imagine as plausible.\n\nHistory is useful when it is treated as a discipline of context. It should not become an analogy machine where every new event is forced into an old template. The point is not to say \"this is 1970s inflation\" or \"this is another Asian financial crisis.\" The point is to ask which constraints, incentives, and policy memories are still alive.\n\nFor macro work, this matters because prices often move before the narrative becomes coherent. Historical context helps separate three things: what is genuinely new, what is a familiar institutional reaction, and what is only a market story looking for authority.\n\nThat is why this site keeps history, politics, and social economics close to market sources. They do not replace the tape. They make the tape more legible.",
    "excerpt": "Markets price the present, but history helps define which futures are imaginable.",
    "readingTimeMinutes": 1,
    "wordCount": 962,
    "path": "/writing/why-market-notebooks-need-history",
    "html": "<p>Markets are forward-looking, but investors are not free from the past. Institutions, political memories, industrial structures, and social expectations all limit what a market can imagine as plausible.</p>\n<p>History is useful when it is treated as a discipline of context. It should not become an analogy machine where every new event is forced into an old template. The point is not to say &quot;this is 1970s inflation&quot; or &quot;this is another Asian financial crisis.&quot; The point is to ask which constraints, incentives, and policy memories are still alive.</p>\n<p>For macro work, this matters because prices often move before the narrative becomes coherent. Historical context helps separate three things: what is genuinely new, what is a familiar institutional reaction, and what is only a market story looking for authority.</p>\n<p>That is why this site keeps history, politics, and social economics close to market sources. They do not replace the tape. They make the tape more legible.</p>\n"
  },
  {
    "id": "why-market-notebooks-need-history-zh",
    "title": "为什么市场笔记需要历史",
    "slug": "why-market-notebooks-need-history",
    "locale": "zh",
    "translationKey": "why-market-notebooks-need-history",
    "status": "published",
    "publishedAt": "2026-04-10",
    "summary": "市场定价当下，但历史帮助我们理解哪些未来是可以被想象的。",
    "tags": [
      "历史",
      "方法",
      "宏观"
    ],
    "featured": false,
    "filePath": "content/posts/2026-04-10-why-market-notebooks-need-history.zh.md",
    "markdown": "市场是向前看的，但投资者并不会真正脱离过去。制度、政治记忆、产业结构和社会预期，都会限制一个市场认为“可能发生”的事情。\n\n历史有用，是因为它提供上下文。它不应该变成一种类比机器，把每个新事件都塞进旧模板里。重点不是说“这就是 1970 年代通胀”，也不是说“这又是一次亚洲金融危机”。重点是问: 哪些约束、激励和政策记忆仍然有效？\n\n这对宏观工作很重要，因为价格常常先于叙事移动。历史语境能帮助我们区分三件事: 什么是真正的新变量，什么是熟悉的制度反应，什么只是市场为了获得解释权而临时拼出的故事。\n\n所以这个网站会把历史、政治和社会经济放在市场信息源旁边。它们不会替代价格本身，但会让价格更容易被理解。",
    "excerpt": "市场定价当下，但历史帮助我们理解哪些未来是可以被想象的。",
    "readingTimeMinutes": 1,
    "wordCount": 300,
    "path": "/zh/writing/why-market-notebooks-need-history",
    "html": "<p>市场是向前看的，但投资者并不会真正脱离过去。制度、政治记忆、产业结构和社会预期，都会限制一个市场认为“可能发生”的事情。</p>\n<p>历史有用，是因为它提供上下文。它不应该变成一种类比机器，把每个新事件都塞进旧模板里。重点不是说“这就是 1970 年代通胀”，也不是说“这又是一次亚洲金融危机”。重点是问: 哪些约束、激励和政策记忆仍然有效？</p>\n<p>这对宏观工作很重要，因为价格常常先于叙事移动。历史语境能帮助我们区分三件事: 什么是真正的新变量，什么是熟悉的制度反应，什么只是市场为了获得解释权而临时拼出的故事。</p>\n<p>所以这个网站会把历史、政治和社会经济放在市场信息源旁边。它们不会替代价格本身，但会让价格更容易被理解。</p>\n"
  }
];
